version: "3.5"

services:
  service:
    build: .
    restart: always
    depends_on:
      - mlflow
    command: ["--store", "http://mlflow:5000", "--store-public", "http://10.10.1.147:5000"]
  mlflow:
    build: ./mlflow
    restart: always
    volumes:
      - mlflow-data:/mlflow-data
    expose:
      - 5000
    ports:
      - "5000:5000"

volumes:
  mlflow-data:
